# -*- coding: utf-8 -*-
"""Code 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSJwTvlmfaVRnVMmvtrzeKkZeppRG22l
"""

import streamlit as st
from transformers import pipeline
import requests

# Set up your ElevenLabs API key
ELEVENLABS_API_KEY = 'cef1f3d8c80a90ccf807cdf25db1aa60'

# Load the Hugging Face translation pipeline
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-es")

def translate_text(text, src_lang, tgt_lang):
    return translator(text, src_lang=src_lang, tgt_lang=tgt_lang)[0]['translation_text']

def text_to_speech(text, voice):
    url = "https://api.elevenlabs.io/api/speech/v2/synthesis"
    payload = {
        "text": text,
        "model": voice
    }
    headers = {
        "Authorization": f"Bearer {ELEVENLABS_API_KEY}",
        "Content-Type": "application/json"
    }
    response = requests.post(url, json=payload, headers=headers)
    return response.content  # Returns audio content

# Streamlit interface
st.title("Real-Time Translator and TTS")
input_text = st.text_area("Enter text to translate:")
src_lang = st.selectbox("Source Language:", options=["English", "Spanish", "French"])
tgt_lang = st.selectbox("Target Language:", options=["English", "Spanish", "French"])
voice_option = st.selectbox("Choose a voice:", options=["Joanna (en-US)", "Matthew (en-US)"])

if st.button("Translate"):
    translated_text = translate_text(input_text, src_lang[:2].lower(), tgt_lang[:2].lower())
    st.write("Translated Text:", translated_text)
    audio_content = text_to_speech(translated_text, voice_option.split()[0])
    st.audio(audio_content, format="audio/mp3")